### ISSUE TITLE
Some Posters were Missing

### ISSUE THREAD

**Issue by KarthiSurfer** [mhdzumair/MediaFusion#173]
@mhdzumair the local deployment and the elfhosted instance both are working properly but some of the poster images were blank and some movies were scraped twice 

using the 3.8.0 version

in the local deployment 

![Screenshot_2024-04-17-10-45-55-521_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/7224b485-ff20-4f82-9256-2703f48e20e9)

in the elfhosted instance 

![Screenshot_2024-04-17-10-46-18-322_com stremio one](https://github.com/mhdzumair/MediaFusion/assets/22189368/7e3b0d17-b1bf-4260-97b3-9997d4a70f3a)

**Comment by Neo402** [comment]
Hi.. @mhdzumair Self-hosted. for me posters are appearing and disappearing again and again.. and some posters are missing as mentioned above.. by @KarthiSurfer

**Comment by mhdzumair** [comment]
What movies are scraped twice? There are only possibilities of duplicate only if the title is having different names (like spaces in between) 

For the poster, it's a bit of an issue. Because these posters are generated on the fly with IMDB rating and logo. Sometimes the server not responding to image data. If the poster is not loading/showing, then click on “Discover” tab and go back to “Home” so stremio will try to re-fetch the image.

**Comment by KarthiSurfer** [comment]
@mhdzumair , in tamil HD movies the following movies were showing twice

Netru Indha Neram
Kaadhal Matum pothum
Radar
#Mayalo

In tamil Old Movies
Cuckoo

Telugu HD movies
Sharma and Ambani

**Comment by mhdzumair** [comment]
The black images due to wrong image URL scraped through TamilBlasters.

The image URL set as `"https://1tamilblasters.pm/applications/core/interface/js/spacer.png"` 
This will work as expected now, however already scraped data won't change unless you manually update it in MongoDB and remove the cached image key in Redis.
