### ISSUE TITLE
Ability to Filter out CAM and Telesynce (TS) files. 

### ISSUE THREAD

**Issue by Jesuninfinity** [mhdzumair/MediaFusion#206]
Kindly at the ability to Filter out CAM and Telesynce files. Would love to only see links for better quality files.

**Comment by mhdzumair** [comment]
@jishnurk I saw you were working on this feature. So instead of adding into the resolution filter, add it separately for quality.  That way it would be easy and clean. 

Also, here are the list of supported qualities in from PTT parser https://github.com/mhdzumair/PTT/blob/main/PTT/handlers.py#L105-L135 . 
- CAM
- TeleSync
- TeleCine
- BluRay REMUX
- BluRay
- UHDRip
- HDRip
- BRRip
- BDRip
- DVDRip
- SCR
- DVD
- PPVRip
- HDTV
- SATRip
- TVRip
- WEB-DLRip
- WEBRip
- WEB-DL
- Unknown (for any other, see the unknown implementation of filter)

**Comment by jishnurk** [comment]
@mhdzumair Thanks for the hint. That was just a hack. So what's your expectation?

1. A new section in config. with checkboxes for selecting quality?
2. Should quality be an option for sorting streams?
3. What about number of streams returned?
4. I also had thoughts about grouping several quality types. So where shall the mapping be done?

**Comment by mhdzumair** [comment]
@jishnurk i can handle the implementation. i started to work on sorting streams by preferred languages. Ill handle quality filter as well.

**Comment by jishnurk** [comment]
@mhdzumair OK. I have anyway pushed some changes (in my fork). Just have a look.

**Comment by mhdzumair** [comment]
Thanks i like the quality map. Ill add my changes on top of yours.

**Comment by mhdzumair** [comment]
Supported in v4.0.0
