### ISSUE TITLE
Catalog listing error .Self hosted instance - help

### ISSUE THREAD

**Issue by sevvian** [mhdzumair/MediaFusion#219]
Hi @mhdzumair ,

First of all thanks for the wonderful plugin , especially south Indian ones .

I have followed your self hosting guide and have installed the media fusion in my home server and tunneled through VPN as reverse proxy . My domain and scraping ,prowlatr service seems working. 

I see the scheduled scrapers are scraping and shows metrics . 

But I have " Issue : whenever I try from stremio application pointing my self hosted instance
![Screenshot_20240629-151952](https://github.com/mhdzumair/MediaFusion/assets/59226487/80e5cdcc-da4a-4346-bc7c-08d17dfa097d)
![Screenshot_20240629-151957](https://github.com/mhdzumair/MediaFusion/assets/59226487/56d33926-9bac-4b51-9462-162352a60625)
ce . "The Catalog" is not loading ,say. " The content did not load .error occured "

Could you pls let me.know how I can troubleshoot ,catalog listing .  Also I see torrents are coming mostly from rarbg,torrentio even though I have many indexers from prowlatr .

Please share your experiences.

Thanks,
Mohanraj

**Comment by mhdzumair** [comment]
1. "The Content did not load is a generic error message" You can first try it from web.stremio.com in the desktop browser, also monitor the network tab and see what's the response you got from the self-hosted instance. And also you could look into mediafusion container, i have added the commands to check logs of container in docker-compose guides. 

2. "torrents are coming mostly from rarbg"  This is because in the live search, mediafusion search it with IMDB id, therefore rarbg is the indexer which responding to IMDB ID queries. Our prowlarr scraping script is highly customizable through env vars. The default vars behavior is to run IMDB search on live call and search it by title in the background task. also, we limited the number of live search torrents count and time. Please check the https://github.com/mhdzumair/MediaFusion/blob/main/docs/configuration.md#scraper-and-scheduler-settings

**Comment by sevvian** [comment]
Thanks bro, I really appreciate your effort and taking time to explain it . Sure I will troubleshoot further. It seems this mostly my instance based issue and not really script issue. I will close the issue .  Thanks again
