### ISSUE TITLE
Pikpak Provider Invalid Credentials 

### ISSUE THREAD

**Issue by Josanity11** [mhdzumair/MediaFusion#291]
Hi,

I have a premium account in Pikpak but Mediafusion (Stremio) says that I have invalid credentials.

Pikpak premium account is a google sign-in and set a password through the settings in the app.

**Comment by mhdzumair** [comment]
Hi @Josanity11 sorry for late reply. I just tested the pikpak integration. it's working fine. Make sure to set the email and password in the setting. https://mypikpak.com/drive/account/bind-email then use the email.  Also note that since PikPak doesn't support the API officially, therefore sometimes the API access getting fail.  as you're premium user, please request them to release an official API to integrate with automation tools.
