### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by barfly14** [mhdzumair/MediaFusion#324]
Using Stremio and I have Real Debrid subscription and have linked it to Media Fusion and installed the addon.
There is a documentary I am trying to play which has many options to try but none play as per the pics shown.
Please could this issue be looked into?
Many thanks
![Screenshot_20241014_205824_Stremio](https://github.com/user-attachments/assets/57932eda-d83b-4cb7-86b8-331782b6fb18)
![Screenshot_20241014_205835_Stremio](https://github.com/user-attachments/assets/cdbec082-ecd0-4ffc-9f4a-0500cd36a5b2)

**Comment by mhdzumair** [comment]
I blacklisted these torrent due to the movie contain .zipx file. If you goto RD you could see that torrent only has .zipx inside of it and when i try to extract that, it contains .scr file which is windows executable file and one .mkv file inside of another folder. This seems to be suspicious. Apart from that I have scanned the .scr file with clamav however i don't find that as vulnerability.

**Comment by barfly14** [comment]
Oh that's shame was looking forward to watching it. Best to be safe though. Thanks for looking into it anyway.
