### ISSUE TITLE
Self-hosted setup. Prowlarr finds results but none, or seemingly random ones are chosen

### ISSUE THREAD

**Issue by dkravetz** [mhdzumair/MediaFusion#354]
Hi! Thank you so much for this amazing project! I have a question/issue understanding how are magnet links chosen.

I am running this self-hosted using docker-compose on version 4.1.5, but this also happened on 4.1.4.

When searching for a given video in a season, I get the following response, which is basically only to update the metadata or to upload my own contribution stream.
![image](https://github.com/user-attachments/assets/42d7e5ee-33d2-4703-bc3e-0a7994dc7f28)

However, if I repeat one of Prowlarr's searches triggered for this video, there is clearly a valid result which is being ignored (there are further results, but this is the one I particularly care about)
![image](https://github.com/user-attachments/assets/f333904c-6e65-4776-b375-b1d49b507e51)

I have RD configured and working; I have disabled a lot of the scrappers that I find irrelevant for my use case
![image](https://github.com/user-attachments/assets/c80cdd73-6e31-4b5d-ac89-e459617a7035)

If I try to manually add a contribution stream with the result I am looking for, I get as a response that it contains no episode data, which is incorrect.

The behavior that I am expecting, and please correct me if I'm wrong in the understanding on how MediaFusion works, is that when a query for a given video is started on a client, the request goes to Prowlarr, which responds with the valid video link(s) to be sent to RD, however, it doesn't seem like the response from Prowlarr is being accepted for some reason. 

Please let me know if you need any more information from my end, and I'll happily provide it.

**Comment by Selmaks** [comment]
I have only just installed it myself so I can't really help much. I tried searching what you searched and got results in Prowlarr but not in media fusion. It seems to find most of the other seasons ok. 

On a different not thanks for the Disable scheduler env. Do you know anymore? I can't seem to find a list I can use. The example env is limited.

**Comment by mhdzumair** [comment]
It might not scrape due to various reason. 
- title not match in the torrent name with movie name or any aka title
- 18+ blacklisted keyword are found which defined in the env. By default, I have defined the following https://github.com/mhdzumair/MediaFusion/blob/6ace7088edbdb66b0fb5dbedd5538d86ab10aa02/db/config.py#L71-L75
- Validate year for movie and series, it's validate between season start year and end year if series end.
- match with season & episode parsing. So when it comes to series it's only one season pack is supported, ignoring the multi season torrent. If you're uploading, then it will look for season & episode validation. 
 
I'm not sure why are you hiding the series name. :)

**Comment by dkravetz** [comment]
I saw someone another comment in another issue where someone spelled Stremi0 or something similar, I just wasn't sure for a possible takedown, it's Scrubs from 2001.

There are no parental filters in place, in the end I gave up, switched to Comet and disabled title match check and everything works as expected. Thank you for the help! I'll close this issue as solved.
