### ISSUE TITLE
Streamed.su support removed?

### ISSUE THREAD

**Issue by icenoir** [mhdzumair/MediaFusion#394]
On the Elfhosted addon I see:
"🏈🏀⚾⚽🏒🏉🎾🏏 Sports Live Events: Watch live sports events from streamed.su, streambtw.com"

on Github I dont see it anymore, but I see:
"🏈🏀⚾⚽🏒🏉🎾🏏 Sports Live Events: Watch live sports events from DaddyLiveHD"

Has the streamed.su website removed from the addon updates? Because I dont see any results from it unfortunately.

**Comment by BRKsays** [comment]
[Yes](https://github.com/mhdzumair/MediaFusion/commit/49cc1b60ebff89f025e54deabbf825bd568a9386).

**Comment by mhdzumair** [comment]
yes, it's removed due to streamed.su limitation on streams. Even though we could scrape the events, the streams video playback is restricted behind Cloudflare validation with their custom implementation.

The flow is like, when user start to play the video, it initiates the cloudflare validation for the destination URL. Then it continuously pings to validation URL. This kind of implementation is totally restricting the usual video player. i could implement a solution with MediaFlow However it's not worth to put my effort since if the owner of the site change to alter the implementation I need to put another effort. 

To answer your earlier question about elfhosted showing the previous detail is due to, I haven't published the latest release
