### ISSUE TITLE
Feature: Add Portuguese (Brazilian) content

### ISSUE THREAD

**Issue by MatadorProBr** [mhdzumair/MediaFusion#50]
The title says it all.

A good source I would recommend is:
https://redecanais.zip/
https://redecanaistv.zip/

**Comment by mhdzumair** [comment]
In v3.6.7, i have added the torrentio stream support. it has more torrent streams. 

BTW, the above links are not working when i just open it in my browser. 
![image](https://github.com/mhdzumair/MediaFusion/assets/44891939/845c69e5-9350-458e-a122-d3f3999aabef)

is this site having regional block?

**Comment by Guatias** [comment]
Hi @mhdzumair, actually Rede Canais is a https stream provider, it is not a torrent site, I believe it is better as there is no depency on seeders to be able to watch the movies or series. Regarding the access, they have a warning message in their site saying to use a VPN if you are having trouble to access it, but in my case, I was having trouble and I simply changed my network config to use google DNS instead of the default, and now I am able to access it, maybe it can work for you as well

**Comment by mhdzumair** [comment]
ohh if it's https stream then this future need to be delay further. Currently, not implemented any sources to scrap HTTPS streams since we have integrated the pikpak and seedr which is free to use within the storage limitation.

**Comment by Guatias** [comment]
got it, I just find out that they provide this alternative link: bit.ly/redecanais10 that does not require a VPN or change your network settings apparently, in case you want to take a look on it in the future

**Comment by mhdzumair** [comment]
Closing as it can be added via prowlarr or jackett indexers
